// Problem:
// Given a singly linked list where each node represents a digit of a positive integer, add 1 to the number represented by the linked list and return the updated linked list.
// The digits are stored from the most significant digit to the least significant digit.

#include <bits/stdc++.h>
using namespace std;

struct ListNode
{
    int val;
    ListNode *next;
    ListNode()
    {
        val = 0;
        next = NULL;
    }
    ListNode(int data1)
    {
        val = data1;
        next = NULL;
    }
    ListNode(int data1, ListNode *next1)
    {
        val = data1;
        next = next1;
    }
};

void printList(ListNode *head)
{
    while (head != NULL)
    {
        cout << head->val << " ";
        head = head->next;
    }
    cout << endl;
}

ListNode *reverseLL(ListNode *head)
{
    if (!head || !head->next)
        return head;

    ListNode *temp = head, *prev = nullptr;

    while (temp)
    {
        ListNode *front = temp->next;
        temp->next = prev;
        prev = temp;
        temp = front;
    }

    return prev;
}

/*
==================================================
ITERATIVE APPROACH

Idea:
Reverse the linked list to process digits from least significant to most significant.
Propagate the carry while adding 1 to each digit.
Reverse the list back and add a new node if a carry remains.

Time Complexity: O(N)
Space Complexity: O(1)
==================================================
*/
// ListNode *addOne(ListNode *head)
// {
//     if (!head)
//         return head;

//     head = reverseLL(head);

//     ListNode *temp = head;

//     int carry = 1;

//     while (temp)
//     {
//         int sum = temp->val + carry;

//         int digit = sum % 10;
//         carry = sum / 10;

//         temp->val = digit;

//         if (carry == 0)
//             break;

//         temp = temp->next;
//     }

//     head = reverseLL(head);

//     if (carry)
//         return new ListNode(carry, head);

//     return head;
// }

/*
==================================================
OPTIMAL APPROACH (RECURSION)

Idea:
Use recursion to reach the last node and add 1 from right to left.
Each recursive call returns the carry generated by the next digit.
If a final carry remains after processing the head node, create a new node.

Time Complexity: O(N)
Space Complexity: O(N) due to recursion stack
==================================================
*/

int recursiveAddOne(ListNode *head)
{
    if (!head)
        return 1;

    int sum = head->val + recursiveAddOne(head->next);

    head->val = sum % 10;

    return sum / 10;
}

ListNode *addOne(ListNode *head)
{
    if (!head)
        return head;

    int finalCarry = recursiveAddOne(head);

    return finalCarry ? new ListNode(finalCarry, head) : head;
}

int main()
{
    ListNode *head1 = new ListNode(1);
    head1->next = new ListNode(3);
    head1->next->next = new ListNode(4);

    head1 = addOne(head1);
    cout << "Result after adding one: ";
    printList(head1);

    return 0;
}