// ==================================================
// PROBLEM
// - Given weights and values of n items, and a capacity W.
// - Find the maximum total value of a chosen subset.
// - Total weight must not exceed the knapsack capacity W.
// ==================================================

#include <bits/stdc++.h>
using namespace std;

// ==================================================
// RECURSIVE APPROACH
//
// Idea:
// - Explore all possible subsets by recursively evaluating whether to include or exclude each individual knapsack item.
// - If included, add the item's value and subtract its weight from the available maximum knapsack capacity.
// - If excluded, skip the item and proceed to the next item with the capacity completely unchanged.
// - Return the maximum overall value generated from both.
//
// Time Complexity: O(2^n) - Two independent choices explored per item.
// Space Complexity: O(n) - Auxiliary space required for the recursion stack.
// ==================================================

int helper(int idx, const vector<int> &wt, const vector<int> &val, int W)
{
    // Base case: Reached the very first item in the array
    if (idx == 0)
    {
        // If the item fits in the remaining capacity, return its value
        if (wt[0] <= W)
            return val[0];
        // Otherwise, it cannot be picked, returning 0
        else
            return 0;
    }

    // Branch 1: Skip the current item and keep the remaining capacity intact
    int notTake = helper(idx - 1, wt, val, W);

    // Branch 2: Pick the current item if it fits within the capacity
    int take = (wt[idx] <= W)
                   ? val[idx] + helper(idx - 1, wt, val, W - wt[idx])
                   : INT_MIN;

    // Return the absolute maximum value between the two choices
    return max(notTake, take);
}

int knapsack01(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Start recursively evaluating from the last item down to the first
    return helper(n - 1, wt, val, W);
}

// ==================================================
// RECURSION + MEMOIZATION (TOP-DOWN DP)
//
// Idea:
// - Optimize the basic recursive approach by dynamically caching overlapping subproblem results within a 2D memoization matrix.
// - The current algorithmic state is uniquely defined by the item index and the remaining knapsack capacity.
// - If a specific state has already been evaluated, return its cached integer value to save time.
//
// Time Complexity: O(n * W) - Each distinct state is computed exactly once.
// Space Complexity: O(n * W) for the DP table + O(n) for the recursion stack.
// ==================================================

int helper(int idx, const vector<int> &wt, const vector<int> &val, int W, vector<vector<int>> &dp)
{
    // Base case: Reached the first item
    if (idx == 0)
    {
        // Return its value if it can successfully fit
        if (wt[0] <= W)
            return val[0];
        else
            return 0;
    }

    // Immediately return the stored result if this subproblem was already solved
    if (dp[idx][W] != -1)
        return dp[idx][W];

    // Branch 1: Skip the current item
    int notTake = helper(idx - 1, wt, val, W, dp);

    // Branch 2: Take the current item if the knapsack capacity allows it
    // NOTE: Adding to INT_MIN safely results in a large negative number, preventing selection
    int take = (wt[idx] <= W)
                   ? val[idx] + helper(idx - 1, wt, val, W - wt[idx], dp)
                   : INT_MIN;

    // Cache the optimal calculated value in the DP table before returning
    return dp[idx][W] = max(notTake, take);
}

int knapsack01(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Initialize a 2D DP matrix filled with -1 to indicate uncomputed states
    vector<vector<int>> dp(n, vector<int>(W + 1, -1));

    // Initiate the top-down recursive calculation
    return helper(n - 1, wt, val, W, dp);
}

// ==================================================
// TABULATION (BOTTOM-UP DP)
//
// Idea:
// - Construct a bottom-up 2D dynamic programming table to systematically accumulate the maximum valid knapsack values iteratively.
// - Base cases are carefully mapped for the very first item across all valid weight capacities available.
// - Iteratively combine the optimal subset values generated by either including or excluding the current knapsack item.
//
// Time Complexity: O(n * W) - Nested loops filling the entire DP table.
// Space Complexity: O(n * W) - Memory specifically allocated for the 2D DP matrix.
// ==================================================

int knapsack01(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Initialize the tabulation matrix with zeros
    vector<vector<int>> dp(n, vector<int>(W + 1, 0));

    // Base case setup: For the first item, populate all capacities where it fits
    for (int w = 0; w <= W; w++)
    {
        if (wt[0] <= w)
            dp[0][w] = val[0];
    }

    // Process the remaining items progressively
    for (int idx = 1; idx < n; idx++)
    {
        // Iterate through all possible knapsack weight capacities
        for (int w = 0; w <= W; w++)
        {
            // Value retrieved if we choose to exclude the current item
            int notTake = dp[idx - 1][w];

            // Value retrieved if we can comfortably include the current item
            int take = (wt[idx] <= w)
                           ? val[idx] + dp[idx - 1][w - wt[idx]]
                           : INT_MIN;

            // Merge both possibilities and save the absolute maximum
            dp[idx][w] = max(notTake, take);
        }
    }

    // The maximum possible value is located at the bottom-right corner
    return dp[n - 1][W];
}

// ==================================================
// 2-ROW SPACE OPTIMIZATION
//
// Idea:
// - Recognize that computing the current dynamic programming row strictly requires only data from the previous row.
// - Replace the large 2D matrix with two compact one-dimensional arrays to drastically reduce overall memory consumption.
// - Systematically update the current array using optimal values retrieved from the previously calculated previous array state.
//
// Time Complexity: O(n * W) - Retains the identical loop iteration count as tabulation.
// Space Complexity: O(W) - Drastically reduced by utilizing just two 1D arrays.
// ==================================================

int knapsack01(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Utilize two single-dimensional arrays for state transition storage
    vector<int> prev(W + 1, 0), curr(W + 1, 0);

    // Initialize the base configuration for the first item across valid weights
    for (int w = wt[0]; w <= W; w++)
    {
        prev[w] = val[0];
    }

    // Evaluate valid value combinations for the rest of the items
    for (int idx = 1; idx < n; idx++)
    {
        // Test every available knapsack capacity
        for (int w = 0; w <= W; w++)
        {
            // Inherited value from the previous item without taking the current one
            int notTake = prev[w];

            // Inherited value from the previous item supplemented with the current item
            int take = (wt[idx] <= w)
                           ? val[idx] + prev[w - wt[idx]]
                           : INT_MIN;

            // Store the best outcome in the newly computed current array
            curr[w] = max(notTake, take);
        }

        // Overwrite the previous state vector with the completed current row
        prev = curr;
    }

    // The definitive answer remains at the maximum capacity index of the previous array
    return prev[W];
}

// ==================================================
// 1-ROW SPACE OPTIMIZATION
//
// Idea:
// - Further optimize memory by using only a single
//   one-dimensional array to store the optimal knapsack values.
// - Process the knapsack capacities strictly in reverse order
//   to prevent overwriting data required for current calculations.
// - This elegantly calculates the current state in place
//   while preserving the strictly required previous state dependencies.
//
// Time Complexity: O(n * W) - Still retains the identical iteration bounds.
// Space Complexity: O(W) - Achieves the absolute minimum memory using just one array.
// ==================================================

int knapsack01(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Utilize a single dimensional array to maintain state transitions in place
    vector<int> prev(W + 1, 0);

    // Populate the base state for the first knapsack item
    for (int w = wt[0]; w <= W; w++)
    {
        prev[w] = val[0];
    }

    // Iterate through all remaining knapsack items
    for (int idx = 1; idx < n; idx++)
    {
        // NOTE: Iterating backward is crucial here to ensure we don't use
        // an updated value from the current row when evaluating 'take'
        for (int w = W; w >= 0; w--)
        {
            // The value if we choose not to take is already sitting in prev[w]
            int notTake = prev[w];

            // Calculate the value if we successfully take the item
            int take = (wt[idx] <= w)
                           ? val[idx] + prev[w - wt[idx]]
                           : INT_MIN;

            // Update the array position in place with the optimal maximum
            prev[w] = max(notTake, take);
        }
    }

    // Return the maximum value found at the extreme end of the array
    return prev[W];
}

int main()
{
    vector<int> wt = {1, 2, 4, 5};
    vector<int> val = {5, 4, 8, 6};

    int W = 5;
    int n = wt.size();

    // Execute the algorithm and display the accumulated maximum value
    int result = knapsack01(wt, val, n, W);

    cout << "The Maximum value of items is " << result << endl;

    return 0;
}
