// ==================================================
// PROBLEM
// - Given weights and values of N items, and knapsack capacity W.
// - Find the maximum total value of a chosen subset of items.
// - An infinite supply of each item is available for selection.
// ==================================================

#include <bits/stdc++.h>
using namespace std;

// ==================================================
// RECURSIVE APPROACH
//
// Idea:
// - Recursively evaluate combinations by choosing to include or exclude the current item based on its weight.
// - Since we have an infinite supply, including an item does not decrement the current item index.
// - Return the maximum value found across all possibilities.
//
// Time Complexity: O(>2^n) - Exponential branching due to infinite item supply.
// Space Complexity: O(W) - Auxiliary space required for the recursion stack.
// ==================================================

int helper(int idx, int W, const vector<int> &wt, const vector<int> &val)
{
    // Base case: Reached the very first item in the array
    if (idx == 0)
    {
        // Calculate how many times this single item fits into the remaining capacity
        return (W / wt[0]) * val[0];
    }

    // Branch 1: Skip the current item and move to the previous one
    int notTake = helper(idx - 1, W, wt, val);

    // Branch 2: Take the current item if it fits within the remaining capacity
    // NOTE: Because of infinite supply, we remain at 'idx' instead of 'idx - 1'.
    // NOTE: Adding val[idx] to -1e9 prevents selection, but returning -1e9 is generally safer against underflow.
    int take = (wt[idx] <= W)
                   ? val[idx] + helper(idx, W - wt[idx], wt, val)
                   : -1e9;

    // Return the absolute maximum value generated from both branches
    return max(notTake, take);
}

int unboundedKnapsack(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Start evaluating combinations recursively from the last item index
    return helper(n - 1, W, wt, val);
}

// ==================================================
// RECURSION + MEMOIZATION (TOP-DOWN DP)
//
// Idea:
// - Optimize the naive exponential recursion by caching overlapping subproblem results in a 2D dynamic programming table.
// - The state is uniquely defined by the current item index and the remaining available knapsack capacity.
// - Retrieve and return cached answers immediately to bypass redundant recursive branching and save significant computation time.
//
// Time Complexity: O(n * W) - Each unique state is computed exactly once.
// Space Complexity: O(n * W) for DP table + O(W) for the recursion stack.
// ==================================================

int helper(int idx, int W, const vector<int> &wt, const vector<int> &val, vector<vector<int>> &dp)
{
    // Base case: Reached the first item denomination
    if (idx == 0)
    {
        // Maximize value by picking as many of the first item as possible
        return (W / wt[0]) * val[0];
    }

    // Immediately return the stored integer result if this state is already solved
    if (dp[idx][W] != -1)
        return dp[idx][W];

    // Evaluate paths where the current item is skipped
    int notTake = helper(idx - 1, W, wt, val, dp);

    // Evaluate paths where the current item is picked (staying on the same index)
    int take = (wt[idx] <= W)
                   ? val[idx] + helper(idx, W - wt[idx], wt, val, dp)
                   : -1e9;

    // Cache the maximum valid value into the matrix before returning
    return dp[idx][W] = max(notTake, take);
}

int unboundedKnapsack(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Initialize a 2D DP matrix filled with -1 to indicate uncomputed states
    vector<vector<int>> dp(n, vector<int>(W + 1, -1));

    return helper(n - 1, W, wt, val, dp);
}

// ==================================================
// TABULATION (BOTTOM-UP DP)
//
// Idea:
// - Construct a bottom-up 2D dynamic programming table to systematically accumulate maximum possible values iteratively.
// - Initialize the first row by taking the maximum occurrences of the first item that fit perfectly.
// - Iteratively combine the optimal subset values generated by either including or excluding the current knapsack item.
//
// Time Complexity: O(n * W) - Nested loops traversing the entire DP table.
// Space Complexity: O(n * W) - Memory specifically allocated for the 2D DP matrix.
// ==================================================

int unboundedKnapsack(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Initialize the tabulation matrix completely with zeros
    vector<vector<int>> dp(n, vector<int>(W + 1, 0));

    // Properly initialize the base state for the very first item
    for (int currW = 0; currW <= W; currW++)
    {
        // Assign the value obtained by picking the maximum possible number of the first item
        dp[0][currW] = (currW / wt[0]) * val[0];
    }

    // Build up the solution iteratively for the remaining items
    for (int idx = 1; idx < n; idx++)
    {
        for (int currW = 0; currW <= W; currW++)
        {
            // Maximum value achieved by ignoring the current item entirely
            int notTake = dp[idx - 1][currW];

            // Maximum value achieved by integrating the current item (reusing the same row index)
            int take = (wt[idx] <= currW)
                           ? val[idx] + dp[idx][currW - wt[idx]]
                           : -1e9;

            // Store the aggregate optimal configuration safely
            dp[idx][currW] = max(notTake, take);
        }
    }

    // Extract the final total maximum value from the bottom-right coordinate
    return dp[n - 1][W];
}

// ==================================================
// 2-ROW SPACE OPTIMIZATION
//
// Idea:
// - Recognize that computing the current dynamic programming row strictly requires data from the previous row and itself.
// - Replace the large two-dimensional matrix with two compact one-dimensional arrays to substantially reduce overall memory usage.
// - Systematically update the current array using combinations safely extracted from the previously calculated optimal array state.
//
// Time Complexity: O(n * W) - Retains the identical loop iteration count as tabulation.
// Space Complexity: O(W) - Drastically reduced by utilizing just two 1D arrays.
// ==================================================

int unboundedKnapsack(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Allocate two 1D arrays to manage state transitions optimally
    vector<int> prev(W + 1, 0), curr(W + 1, 0);

    // Initialize the fundamental base cases strictly for the first item
    for (int currW = 0; currW <= W; currW++)
    {
        prev[currW] = (currW / wt[0]) * val[0];
    }

    // Loop continuously through the array sequentially updating max values
    for (int idx = 1; idx < n; idx++)
    {
        for (int currW = 0; currW <= W; currW++)
        {
            // Fetch the maximum value recorded where this item was skipped previously
            int notTake = prev[currW];

            // Fetch the maximum value where incorporating this item satisfied weight constraints
            // Notice it retrieves data from 'curr' due to the infinite supply property
            int take = (wt[idx] <= currW)
                           ? val[idx] + curr[currW - wt[idx]]
                           : -1e9;

            // Merge possibilities and lock the maximum into the current state array
            curr[currW] = max(notTake, take);
        }

        // Shift the completed current state downward to become the previous state
        prev = curr;
    }

    // Return the fully accumulated integer value resting at the target capacity
    return prev[W];
}

// ==================================================
// 1-ROW SPACE OPTIMIZATION
//
// Idea:
// - Optimize memory further by using a single array to store and update all maximum knapsack values.
// - Since we have an infinite supply of items, we iterate left-to-right to use newly updated values.
// - This perfectly mimics the behavior of the current row while using only one single array structure.
//
// Time Complexity: O(n * W) - Still retains the identical nested iteration bounds.
// Space Complexity: O(W) - Achieves the absolute minimum memory using just one array.
// ==================================================

int unboundedKnapsack(const vector<int> &wt, const vector<int> &val, int n, int W)
{
    // Utilize a single dimensional array to maintain state transitions in place
    vector<int> prev(W + 1, 0);

    // Populate the base state combinations for the first item
    for (int currW = 0; currW <= W; currW++)
    {
        prev[currW] = (currW / wt[0]) * val[0];
    }

    // Iterate through all remaining items
    for (int idx = 1; idx < n; idx++)
    {
        // NOTE: Iterating left-to-right is critical for unbounded knapsack variants.
        // It guarantees that prev[currW - wt[idx]] correctly uses the updated value
        // of the current item index, perfectly simulating an infinite supply.
        for (int currW = 0; currW <= W; currW++)
        {
            // The value if we choose not to take is naturally already in prev[currW]
            int notTake = prev[currW];

            // Calculate the value if we successfully take the item
            int take = (wt[idx] <= currW)
                           ? val[idx] + prev[currW - wt[idx]]
                           : -1e9;

            // Update the array position in place with the optimal maximum
            prev[currW] = max(notTake, take);
        }
    }

    // Return the maximum value found at the extreme end of the array
    return prev[W];
}

int main()
{
    vector<int> wt = {2, 4, 6};

    vector<int> val = {5, 11, 13};

    int W = 10;

    int n = wt.size();

    // Trigger the dynamic programming sequence and display the evaluated answer
    cout << "The Maximum value of items the thief can steal is " << unboundedKnapsack(wt, val, n, W) << endl;

    return 0;
}
