// ==================================================
// PROBLEM
// - Given a rod of length N and an array of prices for each length.
// - Determine the maximum revenue obtainable by cutting the rod.
// - Any number of cuts can be made (infinite supply of lengths).
// ==================================================

#include <bits/stdc++.h>
using namespace std;

// ==================================================
// RECURSIVE APPROACH
//
// Idea:
// - Recursively evaluate combinations by choosing to cut the current rod length or skip it for a smaller length.
// - Since we have an unlimited supply of cuts, taking a cut does not decrement the length index.
// - Return the maximum profit found across all cut possibilities.
//
// Time Complexity: O(>2^n) - Exponential branching due to unlimited cuts.
// Space Complexity: O(N) - Auxiliary space required for the recursion stack.
// ==================================================

int helper(int idx, int N, const vector<int> &price)
{
    // Base case: Reached the 0th index, which represents a rod piece of length 1.
    // A rod of length N can be cut into N pieces of length 1.
    if (idx == 0)
        return N * price[0];

    // Branch 1: Skip the current piece length and move to a smaller one
    int notTake = helper(idx - 1, N, price);

    // Convert 0-based array index to actual 1-based rod length
    int rodLength = idx + 1;

    // Branch 2: Take the current piece if it fits in the remaining uncut rod
    // NOTE: We do not decrement 'idx' here because we have an unlimited supply of this length
    int take = (rodLength <= N)
                   ? price[idx] + helper(idx, N - rodLength, price)
                   : -1e9;

    // Return the maximum revenue generated from both branching choices
    return max(notTake, take);
}

int rodCutting(const vector<int> &price, int n)
{
    // Start evaluating combinations recursively from the largest possible cut piece
    return helper(n - 1, n, price);
}

// ==================================================
// RECURSION + MEMOIZATION (TOP-DOWN DP)
//
// Idea:
// - Optimize the naive exponential recursion by caching overlapping subproblem results dynamically inside a 2D memoization table.
// - The state is defined by the current piece index combined with the remaining uncut rod length available.
// - Retrieve cached answers immediately to bypass redundant branching.
//
// Time Complexity: O(n * N) - Each unique state is computed exactly once.
// Space Complexity: O(n * N) for DP table + O(N) for recursion stack.
// ==================================================

int helper(int idx, int N, const vector<int> &price, vector<vector<int>> &dp)
{
    // Base case: Maximize revenue by using only pieces of length 1
    if (idx == 0)
        return N * price[0];

    // Immediately return the stored integer result if this state is already solved
    if (dp[idx][N] != -1)
        return dp[idx][N];

    // Evaluate paths where the current piece length is skipped
    int notTake = helper(idx - 1, N, price, dp);

    int rodLength = idx + 1;

    // Evaluate paths where the current piece length is utilized
    int take = (rodLength <= N)
                   ? price[idx] + helper(idx, N - rodLength, price, dp)
                   : -1e9;

    // Cache the maximum valid value into the matrix before returning
    return dp[idx][N] = max(notTake, take);
}

int rodCutting(const vector<int> &price, int n)
{
    // Initialize a 2D DP matrix filled with -1 to indicate uncomputed states
    vector<vector<int>> dp(n, vector<int>(n + 1, -1));

    return helper(n - 1, n, price, dp);
}

// ==================================================
// TABULATION (BOTTOM-UP DP)
//
// Idea:
// - Construct a bottom-up 2D dynamic programming table to systematically accumulate maximum possible revenues iteratively without recursion.
// - Initialize the first row for cuts of length one.
// - Iteratively combine the optimal subset values generated by either including or excluding the current rod piece length.
//
// Time Complexity: O(n * N) - Nested loops traversing the entire DP table.
// Space Complexity: O(n * N) - Memory specifically allocated for the 2D DP matrix.
// ==================================================

int rodCutting(const vector<int> &price, int n)
{
    // Initialize the tabulation matrix
    vector<vector<int>> dp(n, vector<int>(n + 1, 0));

    // Properly initialize the base state for cuts of length 1
    for (int N = 0; N <= n; N++)
    {
        dp[0][N] = N * price[0];
    }

    // Build up the solution iteratively for the remaining piece lengths
    for (int idx = 1; idx < n; idx++)
    {
        for (int N = 0; N <= n; N++)
        {
            // Revenue achieved by ignoring the current piece length
            int notTake = dp[idx - 1][N];

            int rodLength = idx + 1;

            // Revenue achieved by utilizing the current piece length
            int take = (rodLength <= N)
                           ? price[idx] + dp[idx][N - rodLength]
                           : -1e9;

            // Store the optimal configuration safely
            dp[idx][N] = max(notTake, take);
        }
    }

    // Extract the final total maximum value from the bottom-right coordinate
    return dp[n - 1][n];
}

// ==================================================
// 2-ROW SPACE OPTIMIZATION
//
// Idea:
// - Recognize that computing the current dynamic programming row strictly requires data from the previous row and itself.
// - Replace the large two-dimensional matrix with two compact one-dimensional arrays to substantially reduce overall memory usage.
// - Systematically update the current array using previously calculated values.
//
// Time Complexity: O(n * N) - Retains the identical loop iteration count as tabulation.
// Space Complexity: O(N) - Drastically reduced by utilizing just two 1D arrays.
// ==================================================

int rodCutting(const vector<int> &price, int n)
{
    // Allocate two 1D arrays to manage state transitions optimally
    vector<int> prev(n + 1, 0), curr(n + 1, 0);

    // Initialize the fundamental base cases strictly for length 1 pieces
    for (int N = 0; N <= n; N++)
    {
        prev[N] = N * price[0];
    }

    // Loop continuously through the array sequentially updating max values
    for (int idx = 1; idx < n; idx++)
    {
        for (int N = 0; N <= n; N++)
        {
            // Fetch the maximum value recorded where this piece was skipped previously
            int notTake = prev[N];

            int rodLength = idx + 1;

            // Fetch the maximum value where incorporating this piece was valid
            // Notice it retrieves data from 'curr' due to the infinite supply property
            int take = (rodLength <= N)
                           ? price[idx] + curr[N - rodLength]
                           : -1e9;

            // Merge possibilities and lock the maximum into the current state array
            curr[N] = max(notTake, take);
        }

        // Shift the completed current state downward to become the previous state
        prev = curr;
    }

    // Return the fully accumulated integer value resting at the target capacity
    return prev[n];
}

// ==================================================
// 1-ROW SPACE OPTIMIZATION
//
// Idea:
// - Optimize memory further by using a single one-dimensional array to store and update all maximum cut values.
// - Because we can reuse pieces, we iterate left-to-right to correctly utilize the newly updated values in-place.
//
// Time Complexity: O(n * N) - Still retains the identical nested iteration bounds.
// Space Complexity: O(N) - Achieves the absolute minimum memory using just one array.
// ==================================================

int rodCutting(const vector<int> &price, int n)
{
    // Utilize a single dimensional array to maintain state transitions in place
    vector<int> prev(n + 1, 0);

    // Populate the base state combinations for the first length piece
    for (int N = 0; N <= n; N++)
    {
        prev[N] = N * price[0];
    }

    // Iterate through all remaining rod piece lengths
    for (int idx = 1; idx < n; idx++)
    {
        // NOTE: Iterating left-to-right is critical for unbounded supply DP variations.
        // It guarantees that prev[N - rodLength] correctly uses the newly updated value
        // of the current item index, perfectly simulating an infinite supply.
        for (int N = 0; N <= n; N++)
        {
            // The value if we choose not to take is naturally already in prev[N]
            int notTake = prev[N];

            int rodLength = idx + 1;

            // Calculate the value if we successfully take the piece
            int take = (rodLength <= N)
                           ? price[idx] + prev[N - rodLength]
                           : -1e9;

            // Update the array position in place with the optimal maximum
            prev[N] = max(notTake, take);
        }
    }

    // Return the maximum value found at the extreme end of the array
    return prev[n];
}

int main()
{
    vector<int> price = {2, 4, 6, 8};

    int n = price.size();

    // Trigger the dynamic programming sequence and display the evaluated answer
    cout << "The Maximum value is " << rodCutting(price, n) << endl;

    return 0;
}
